site_name: Aprenentatge de llengües mitjançant progamari lliure
site_url: https://cursos-cefire.github.io/aprenentatge-idiomes-software-lliure/
docs_dir: 'content'
site_dir: 'docs'
nav:
    - Inici: index.md
    - Unitat 0:
      - Revisió del perfil i presentació dels participants: unitat 0/index.md
      - Tasques de la unitat 0: unitat 0/tasques.md
    - Unitat 1:
      - Programari lliure: unitat 1/programari lliure.md
      - Creació de recursos H5P: unitat 1/h5p.md
    #     - CD/CI: Unitats/Unitat 1/CD-CI.md
    #   - Unitat 3 - Detecció i correcció de vulnerabilitats en aplicacions web:
    #     - API Rest: Unitats/Unitat 3/APIRest.md
    # - About: about.md
theme:
  name: material
  language: ca
plugins:
    - mkdocs-video
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences