site_name: Aprenentatge de llengües mitjançant progamari lliure
site_url: https://cursos-cefire.github.io/aprenentatge-idiomes-software-lliure/
docs_dir: 'content'
site_dir: 'docs'
nav:
    - Inici: index.md
    - Unitat 0 - Presentació:
      - Revisió del perfil i presentació dels participants: unitat 0/index.md
      - Tasques de la unitat 0: unitat 0/tasques.md
    - Unitat 1 - H5P:
      - Programari lliure: unitat 1/programari lliure.md
      - Creació de recursos H5P: unitat 1/h5p.md
      - Tasques de la unitat 1 - Creació de recursos H5P: unitat 1/tasques.md
    - Unitat 2 - Edició d'imatges: 
      - Introducció: unitat 2/introduccio.md
      - Inkscape - introducció: unitat 2/Introducció a inkscape.md
      - Inkscape - creació i modificació de recursos: unitat 2/Inkscape - creació de recursos amb inkscape.md
      - Tasques de la unitat 2: unitat 2/tasques.md
    - Unitat 3 - Edició d'àudio:
      - Introducció: unitat 3/introduccio.md
      - Edició amb audacity: unitat 3/audacity.md
      - Tasques: unitat 3/tasques.md
theme:
  name: material
  language: ca
  favicon: img/faviconV2.png
  logo: img/favicon.png
plugins:
    - mkdocs-video
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences